// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /todo)
	CreateTodoItem(ctx echo.Context) error

	// (DELETE /todo/{id})
	DeleteTodoItem(ctx echo.Context, id TodoParams) error

	// (GET /todo/{id})
	GetTodoItem(ctx echo.Context, id TodoParams) error

	// (PUT /todo/{id})
	UpdateTodoItem(ctx echo.Context, id TodoParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateTodoItem converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTodoItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateTodoItem(ctx)
	return err
}

// DeleteTodoItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTodoItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id TodoParams

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteTodoItem(ctx, id)
	return err
}

// GetTodoItem converts echo context to params.
func (w *ServerInterfaceWrapper) GetTodoItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id TodoParams

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTodoItem(ctx, id)
	return err
}

// UpdateTodoItem converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTodoItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id TodoParams

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateTodoItem(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/todo", wrapper.CreateTodoItem)
	router.DELETE(baseURL+"/todo/:id", wrapper.DeleteTodoItem)
	router.GET(baseURL+"/todo/:id", wrapper.GetTodoItem)
	router.PUT(baseURL+"/todo/:id", wrapper.UpdateTodoItem)

}
