// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xTTY/TMBD9K2HgGDVZuOXGh4QqDnBYToiDiWfbWTUeM54uWlX+78jjtmnVHDggxDHj",
	"Z7+PeTnAyFPkgEETDAeITtyEimJfyp6/lIl9eRyFohIHGIDCAzf76J2ihxaozKLTLbQQ3IQFUeaCP/ck",
	"6GFQ2WMLadzi5Ozt52iooLhBgZzz6dTI7tnzWnEyUcIRRQmPMtKs4/xOUqGwgXyiXziIQiykz4vs7WnE",
	"Px5x1KqnmDQ06a6c3W8pNZQa15Rkmh0lhRaeUFINpV/1q7tCxRGDiwQDvFndrXpoLRuT35Wr5oqT3viB",
	"94JOMTUBfzWkODUUZrIW7GlxBbz2Z/g5rBo4Jn3H3nyOHBSD8bgYdzTa1e4x1fDmdbwSfIABXnZzH7rj",
	"Orrz89lSEUyRQ6rbeN33tyY+f3pxxJrb7kA+V9QO1ZZz7eKDzS9cXNbw27K4GdJd1DR//xN9hammKzjx",
	"E/q67g0uLGRdiv52HDHWpl8r/4j672QfY20h7vU2xK/2M/49Nf9Bj6olX8uU8+8AAAD//6Tsi+CtBAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
