// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

// TodoItem defines model for TodoItem.
type TodoItem struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Priority    *int    `json:"priority,omitempty"`
}

// TodoParams defines model for todoParams.
type TodoParams = int

// CreateTodoItemJSONRequestBody defines body for CreateTodoItem for application/json ContentType.
type CreateTodoItemJSONRequestBody = TodoItem

// UpdateTodoItemJSONRequestBody defines body for UpdateTodoItem for application/json ContentType.
type UpdateTodoItemJSONRequestBody = TodoItem
